version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: doggo
      POSTGRES_PASSWORD: doggoGO123
      POSTGRES_DB: doggo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: